title: Big Data Structure Engineer
author: Mengzhu He
description: Personal Portfolio

include:
  - _includes

collections:
  pages:
    output: true

remote_theme: pages-themes/architect@v0.2.0


  